### ISSUE TITLE
Implement build command

### ISSUE THREAD

**Issue by chriskrycho** [chriskrycho/lightning-rs#19]
- [x] get list of docs in source directory (#2, #11)
- [ ] parse YAML metadata (#18)
- [ ] parse Markdown
    - [x] with pandoc (1d624565)
    - [ ] with cmark-pulldown
- [x] syntax-highlight code blocks (#6)
- [ ] render into templates
    - [ ] index
    - [ ] per-taxonomy templates
- [ ] render into RSS feed (#5)
