### ISSUE TITLE
Load all configuration data

### ISSUE THREAD

**Issue by chriskrycho** [chriskrycho/lightning-rs#20]
- [x] directories: content, output, and template (#11, 3603c0a7)
- [x] basic site metadata (#23)
- [x] structure and taxonomies (#21)
